apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-cloud-buckets
  annotations:
    meta.crossplane.io/maintainer: Upbound <atorgerson@upbound.io>
    meta.crossplane.io/source: github.com/garreeoke/cfg-buckets
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Config to build buckets on aws, gke, and azure
    meta.crossplane.io/readme: |
      Config to build buckets on aws, gke, and azure
spec:
  crossplane:
    version: ">=v1.12.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-s3
      version: ">=v0.36.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v0.36.0"
    - provider: xpkg.upbound.io/upbound/provider-azure-storage
      version: ">=v0.33.0"