apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcloudbuckets.cfg.upbound.io
spec:
  group: cfg.upbound.io
  names:
    kind: XCloudBucket
    plural: xcloudbuckets
  claimNames:
    kind: CloudBucket
    plural: cloudbuckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: "Create generic cloud bucket and policy for the desired cloud"
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: "id"
                placement:
                  type: string
                  description: "Depending on cloud it will be either a region, a resource group or ..."
                other:
                  type: string
                  description: "Another parameter such as resource group or something else needed"
                compositionSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      properties:
                        cloud:
                          type: string
                          description:
                          enum:
                            - aws
                            - azure
                            - google
                      required:
                        - cloud
                  required:
                    - matchLabels
              required:
                - id
                - placement
                - compositionSelector