apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: torgblargblarg
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: "West US 3"
    resourceGroupName: "torg-rg1"
